language : go

go :
    - 1.6

before_install:
    - go get -u github.com/golang/protobug/protoc-gen-go
    - sudo apt-get update
    - sudo apt-get install autoconf automake libtool curl make g++ unzip
    - git clone https://github.com/google/protobuf.git
    - cd protobuf
    - git submodule update --init --recursive
    - ./autogen.sh
    - ./configure
    - make && make check && sudo make install && sudo ldconfig

install:
    - go get -d ./...
    - cd src/chord/ && go build
